import { v4 as uuid } from "uuid";
import {
  productOne,
  productTwo,
  productThree,
  productFour,
  productFive,
  productSix,
  productSeven,
  productEight,
  productNine,
  productTen,
  productEleven,
  productTwelve,
} from "../../assets";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Red T-Shirt",
    price: "999",
    discount: "40",
    categoryName: "T-Shirts",
    rating: "4",
    inStock: true,
    isFeatured: true,
    isLatest: false,
    badge: "New",
    imageSrc: productOne,
    description:
      "Give your summer wardrobe a style upgrade with this Men's Active T-Shirt.Team it with a pair of shorts for your morning workout or a denims for an evening out.",
    sizes: ["XXL", "XL", "L", "M"],
  },
  {
    _id: uuid(),
    title: "Black Sneakers",
    price: "1299",
    discount: "30",
    categoryName: "Sneakers",
    rating: "3",
    inStock: true,
    isFeatured: false,
    isLatest: true,
    badge: "New",
    imageSrc: productTwo,
    description:
      "Give your shoe wardrobe a style upgrade with these Black Sneakers.Team it with a pair of shorts for your morning workout or a denims for an evening out.",
    sizes: ["10", "11", "12"],
  },
  {
    _id: uuid(),
    title: "Gray Track",
    price: "499",
    discount: "20",
    categoryName: "Tracks",
    rating: "3",
    inStock: true,
    isFeatured: false,
    isLatest: false,
    badge: "",
    imageSrc: productThree,
    description:
      "Give your summer wardrobe a style upgrade with this Gray Track.Team it with a pair of shorts for your morning workout or a denims for an evening out.",
    sizes: ["28", "32", "34", "36", "38"],
  },
  {
    _id: uuid(),
    title: "Blue T-Shirt",
    price: "799",
    discount: "45",
    categoryName: "T-Shirts",
    rating: "4",
    inStock: true,
    isFeatured: false,
    isLatest: true,
    badge: "New",
    imageSrc: productFour,
    description:
      "Give your summer wardrobe a style upgrade with this Men's Active T-Shirt.Team it with a pair of shorts for your morning workout or a denims for an evening out.",
    sizes: ["L", "M"],
  },
  {
    _id: uuid(),
    title: "White Sneakers",
    price: "1299",
    discount: "30",
    categoryName: "Sneakers",
    rating: "5",
    inStock: true,
    isFeatured: true,
    isLatest: false,
    badge: "",
    imageSrc: productFive,
    description:
      "Give your shoe wardrobe a style upgrade with these White Sneakers.Team it with a pair of shorts for your morning workout or a denims for an evening out.",
    sizes: ["11", "12"],
  },
  {
    _id: uuid(),
    title: "Black T-Shirt",
    price: "499",
    discount: "20",
    categoryName: "T-Shirts",
    rating: "4",
    inStock: true,
    isFeatured: false,
    isLatest: true,
    badge: "New",
    imageSrc: productSix,
    description:
      "Give your summer wardrobe a style upgrade with this Men's Active Black T-Shirt.Team it with a pair of shorts for your morning workout or a denims for an evening out.",
    sizes: ["XL", "L"],
  },
  {
    _id: uuid(),
    title: "Pair of Socks",
    price: "499",
    discount: "10",
    categoryName: "Sneakers",
    rating: "2",
    inStock: false,
    isFeatured: false,
    isLatest: false,
    badge: "",
    imageSrc: productSeven,
    description:
      "Give your shoe wardrobe a style upgrade with these Pair Of Socks.Team it with a pair of shorts for your morning workout or a denims for an evening out.",
    sizes: ["9", "10", "12"],
  },
  {
    _id: uuid(),
    title: "Black Watch",
    price: "1499",
    discount: "20",
    categoryName: "Watches",
    rating: "4",
    inStock: true,
    isFeatured: true,
    isLatest: false,
    badge: "",
    imageSrc: productEight,
    description:
      "Give your watch collection a style upgrade with this Black Watch.Team it with Formal or Casual Wears.",
    sizes: ["36", "38", "42", "46"],
  },
  {
    _id: uuid(),
    title: "Black and Yellow Watch",
    price: "2999",
    discount: "20",
    categoryName: "Watches",
    rating: "5",
    inStock: true,
    isFeatured: true,
    isLatest: false,
    badge: "New",
    imageSrc: productNine,
    description:
      "Give your watch collection a style upgrade with this Black and Yellow Watch.Team it with Formal or Casual Wears.",
    sizes: ["38", "42", "46"],
  },
  {
    _id: uuid(),
    title: "Black Sports Shoes",
    price: "999",
    discount: "10",
    categoryName: "Sneakers",
    rating: "3",
    inStock: true,
    isFeatured: false,
    isLatest: true,
    badge: "",
    imageSrc: productTen,
    description:
      "Give your shoe wardrobe a style upgrade with these Black Sports Shoes.Team it with a pair of shorts for your morning workout or a denims for an evening out.",
    sizes: ["10", "12"],
  },
  {
    _id: uuid(),
    title: "White Loafers",
    price: "899",
    discount: "10",
    categoryName: "Sneakers",
    rating: "4",
    inStock: true,
    isFeatured: true,
    isLatest: false,
    badge: "",
    imageSrc: productEleven,
    description:
      "Give your shoe wardrobe a style upgrade with these White Loafers.Team it with Formal or Casual Wears.",
    sizes: ["9", "12"],
  },
  {
    _id: uuid(),
    title: "Black Track",
    price: "499",
    discount: "0",
    categoryName: "Tracks",
    rating: "2",
    inStock: true,
    isFeatured: true,
    isLatest: false,
    badge: "",
    imageSrc: productTwelve,
    description:
      "Give your summer wardrobe a style upgrade with this Black Track.Team it with a pair of shorts for your morning workout or a denims for an evening out.",
    sizes: ["34", "36", "38"],
  },
];
